services:
  mysql-db:
    image: container-registry.oracle.com/mysql/community-server:8.2
    container_name: mysql-db
    ports:
      - "1306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rmdb
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - rm-net
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost" ]
      interval: 10s
      timeout: 5s
      retries: 3

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql-db
      PMA_PORT: 3306
    networks:
      - rm-net

volumes:
  mysql-data: {}

networks:
  rm-net:
    driver: bridge